"""add_autoincrement_to_user_id

Revision ID: 7baffdcf5338
Revises: 4ae17454dd37
Create Date: 2025-07-28 16:40:13.896002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7baffdcf5338'
down_revision: Union[str, Sequence[str], None] = '4ae17454dd37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE users_user_id_seq')
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               server_default=sa.text("nextval('users_user_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False,
               server_default=None)
    op.execute('DROP SEQUENCE users_user_id_seq')
    # ### end Alembic commands ###