"""Add composite unique constraint to places

Revision ID: b784df7f288e
Revises: d1fdafcb32f4
Create Date: 2025-07-30 14:45:55.177964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b784df7f288e'
down_revision: Union[str, Sequence[str], None] = 'd1fdafcb32f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_constraint(op.f('places_name_key'), 'places', type_='unique')
    op.create_unique_constraint('_name_lat_lng_uc', 'places', ['name', 'lat', 'lng'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_lat_lng_uc', 'places', type_='unique')
    op.create_unique_constraint(op.f('places_name_key'), 'places', ['name'], postgresql_nulls_not_distinct=False)
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_pkey'))
    )
    # ### end Alembic commands ###
