"""Add title, thumbnail_url, youtube_url to contents table

Revision ID: fa5bafca312d
Revises: b784df7f288e
Create Date: 2025-08-01 17:18:30.109389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5bafca312d'
down_revision: Union[str, Sequence[str], None] = 'b784df7f288e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contents', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment=None,
               existing_comment='youtube 영상 제목',
               existing_nullable=True)
    op.alter_column('contents', 'thumbnail_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment=None,
               existing_comment='youtube thumbnail url',
               existing_nullable=True)
    op.alter_column('contents', 'youtube_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True,
               comment=None,
               existing_comment='youtube url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contents', 'youtube_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               comment='youtube url')
    op.alter_column('contents', 'thumbnail_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment='youtube thumbnail url',
               existing_nullable=True)
    op.alter_column('contents', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment='youtube 영상 제목',
               existing_nullable=True)
    # ### end Alembic commands ###
